name: Build
on:
  pull_request:
  push:
    branches:
      - master
permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1 # v1.144.2
        with:
          bundler-cache: true
      - name: Bootstrap
        run: bundle exec rake bootstrap
      - name: Set remote URL
        run: |
          git config --global user.email "$(git log -1 --pretty=format:'%ae')"
          git config --global user.name "$(git log -1 --pretty=format:'%an')"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY"
      - name: Build
        if: github.event_name == 'pull_request'
        run: bundle exec rake build
      - name: Deploy
        if: github.event_name != 'pull_request'
        run: bundle exec rake deploy
